version: '3.1'

services:

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --bind_ip=0.0.0.0 --logpath=/dev/null
    ports:
      - 27017:27017

  server:
    #image: deviavir/zenbot:unstable
    image: myzenbot
    volumes:
      - ./conf.js:/app/conf.js
      - ./extensions:/app/extensions
      - ./simulations:/app/simulations
      - ./models:/app/models
    links:
      - mongodb
    command: [ "trade", "--paper", "--strategy", "raj"]
    restart: always
    tty: true
    depends_on:
      - mongodb
    environment:
      - MONGODB_PORT_27017_TCP_ADDR=mongodb
    ports:
      - 20040:20040

  # Remove below comments to use this container. "adminMongo is a Web based user interface (GUI) to handle all your MongoDB connections/databases needs."
  #
  #adminmongo:
  #  image: mrvautin/adminmongo
  #  links:
  #    - mongodb
  #  tty: true
  #  ports:
  #    - "1234:1234"
  #  environment:
  #    - CONN_NAME=zenbot_mongodb
  #    - DB_HOST=mongodb
  #    - DB_PORT=27017
  #  command: "npm start"
